from animate import PyAnimate
a = PyAnimate()

a.make_kickflip_gif()
a.make_heelflip_gif()
a.make_bs_360_shuv_gif()
a.make_fs_360_shuv_gif()
a.make_front_foot_impossible_gif()
a.make_back_foot_impossible_gif()
a.make_treflip_gif()
a.make_lazerflip_gif()
a.make_hardflip_gif()
a.make_inward_heelflip_gif()
a.make_varial_heelflip_gif()
a.make_varial_kickflip_gif()
